### ISSUE TITLE
Unable to get a token

### ISSUE THREAD

**Issue by Baksaya** [AstraaDev/Fake-Verification-Bot#12]
Hi ! I have a problem

![image](https://user-images.githubusercontent.com/126328658/221412933-55779537-c7e9-4247-b481-35845bd9a6b2.png)
![image](https://user-images.githubusercontent.com/126328658/221412981-f1bf5f66-2fe5-42fe-a6d4-cc6bbe774a62.png)

You have a solution please ?

**Comment by AstraaDev** [comment]
Yes, but I don't plan to release the patch publicly.
Have a nice day! :)
