### ISSUE TITLE
:fire: 

### ISSUE THREAD

**Issue by cipherwithadot** [AstraaDev/Fake-Verification-Bot#7]
your code is being used and has taken over discord, thats sick, have fun my g

**Comment by AstraaDev** [comment]
I don't know if it's ironic, but my work was never created to be used in a malicious way. I noticed that it was used to scam other people and I'm sorry about that.
I'm thinking of deleting this directory to avoid further damage.

**Comment by TechStudent11** [comment]
You might want to check NTTS's video...

https://www.youtube.com/watch?v=U3hEFSV1THA

**Comment by AstraaDev** [comment]
Yes, I've heard about it. And even if its purpose was to prevent, I am afraid that it makes this project even more known and consequently, that many new scams appear.

**Comment by rcmaehl** [comment]
I'd recommend setting the repo(s) to contributors only for now community hiveminds can be a bit... crazy.

**Comment by DEVTomatoCake** [comment]
Hell @AstraaDev delete it now or github will do it

**Comment by TechStudent11** [comment]
> Hell @AstraaDev delete it now or github will do it

No threats.
